### ISSUE TITLE
Error walking through directories

### ISSUE THREAD

**Issue by jorti** [thedonvaughn/cover_grabber#1]
I got this error while fetching the covers. It fails always in the same directory but I don't know which one.

Traceback (most recent call last):
  File "/usr/bin/covergrabber", line 59, in <module>
    main()
  File "/usr/bin/covergrabber", line 56, in main
    media_walker = MediaDirWalker(opts["media_dir"], opts["overwrite"]).do_walk_path()
  File "/usr/lib/python2.7/site-packages/cover_grabber/media_dir_walker.py", line 33, in do_walk_path
    os.path.walk(self.path, self.process_dir, None)
  File "/usr/lib64/python2.7/posixpath.py", line 237, in walk
    walk(name, func, arg)
  File "/usr/lib64/python2.7/posixpath.py", line 237, in walk
    walk(name, func, arg)
  File "/usr/lib64/python2.7/posixpath.py", line 229, in walk
    func(arg, top, names)
  File "/usr/lib/python2.7/site-packages/cover_grabber/media_dir_walker.py", line 58, in process_dir
    downloader = LastFMDownloader(album_name, artist_name) # Set downloader type to be LastFM
  File "/usr/lib/python2.7/site-packages/cover_grabber/lastfm_downloader.py", line 31, in **init**
    self.url = self.format_url()
  File "/usr/lib/python2.7/site-packages/cover_grabber/lastfm_downloader.py", line 35, in format_url
    return self.LASTFM_URL.format(album_name=self.album_name)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)

**Comment by jorti** [comment]
More info: the directory has some chinese characters.

**Comment by ergo** [comment]
jorti all of this is already fixed in my fork - grab it to test - when the author wakes up probably the changes will get pulled to official repo

**Comment by ergo** [comment]
this had been pulled into main repository so the issue can be closed now

**Comment by thedonvaughn** [comment]
Hi,
I just released version 1.1.0
I added UTF-8 support.  It should fix this issue.  Please download it and
try again.

Thanks.

On Fri, Dec 9, 2011 at 4:21 AM, Juan Orti Alcaine <
reply@reply.github.com

> wrote:
> 
> I got this error while fetching the covers. It fails always in the same
> directory but I don't know which one.
> 
> Traceback (most recent call last):
>  File "/usr/bin/covergrabber", line 59, in <module>
>    main()
>  File "/usr/bin/covergrabber", line 56, in main
>    media_walker = MediaDirWalker(opts["media_dir"],
> opts["overwrite"]).do_walk_path()
>  File
> "/usr/lib/python2.7/site-packages/cover_grabber/media_dir_walker.py", line
> 33, in do_walk_path
>    os.path.walk(self.path, self.process_dir, None)
>  File "/usr/lib64/python2.7/posixpath.py", line 237, in walk
>    walk(name, func, arg)
>  File "/usr/lib64/python2.7/posixpath.py", line 237, in walk
>    walk(name, func, arg)
>  File "/usr/lib64/python2.7/posixpath.py", line 229, in walk
>    func(arg, top, names)
>  File
> "/usr/lib/python2.7/site-packages/cover_grabber/media_dir_walker.py", line
> 58, in process_dir
>    downloader = LastFMDownloader(album_name, artist_name) # Set downloader
> type to be LastFM
>  File
> "/usr/lib/python2.7/site-packages/cover_grabber/lastfm_downloader.py", line
> 31, in **init**
>    self.url = self.format_url()
>  File
> "/usr/lib/python2.7/site-packages/cover_grabber/lastfm_downloader.py", line
> 35, in format_url
>    return self.LASTFM_URL.format(album_name=self.album_name)
> UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3:
> ordinal not in range(128)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/thedonvaughn/cover_grabber/issues/1

## 

Jayson Vaughn vaughn.jayson@gmail.com
GnuPG: 10D06AB4
